---
- name: provision test instances
  hosts: localhost
  tasks:
  - name: create instances
    os_server:
      state: present
      auth:
        username: "{{ os_login }}"
        password: "{{ os_password }}"
        project_name: "{{ os_tenant_name }}"
        auth_url: "{{ auth_url }}"
      name: "{{ instance_name }}"
      image: "{{ image_id }}"
      flavor: "{{ flavor_id }}"
      key_name: "{{ key_name }}"
