- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Nuke it if it exists
    shell: rm -rf {{ ref_name }}*
    args:
      chdir: ~/www/ci-logs

  - name: Create ref directory on web server
    shell: mkdir ~/www/ci-logs/{{ ref_name }}

  - name: Copy files to web server
    copy: src={{ results_dir }}/{{ item }} dest=~/www/ci-logs/{{ ref_name }}
    ignore_errors: yes
    with_items:
      - ansible.out
      - stack.sh.log.out
      - "{{ ref_name }}.tar.gz"

  - name: Untar log files on web
    shell: tar -xzf {{ ref_name }}.tar.gz
    ignore_errors: yes
    args:
      chdir: ~/www/ci-logs/{{ ref_name }}

