- hosts: localhost
  connection: local
  tasks:
  - include_vars: vars.yml
  - name: Shut down instance
    os_server:
      state: absent
      cloud: "{{ cloud_name }}"
      name: "{{ instance_name }}"
