- hosts: localhost
  connection: local
  tasks:
  - include_vars: vars.yml
  - name: Shut down instance
    os_server:
      state: absent
      auth:
        username: "{{ os_login }}"
        password: "{{ os_password }}"
        project_name: "{{ os_tenant_name }}"
        auth_url: "{{ auth_url }}"
      name: "{{ instance_name }}"
