- hosts: devstack_instances
  tasks:

  - name: send over eth1.cfg
    become: yes
    template: src=../../templates/eth1.cfg dest=/etc/network/interfaces.d/eth1.cfg

  - name: enable eth1
    become: yes
    shell: ifup eth1
