- hosts: devstack_instances
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
    chefdk: chefdk_1.0.3-1_amd64.deb

  tasks:

  - name: fixup hosts file
    become: yes
    lineinfile:
      dest: /etc/hosts
      regexp: '^127\.0\.0\.1'
      line: "127.0.0.1 localhost {{ iname }}"

  - name: create workspace
    shell: mkdir /home/ubuntu/logs

  - name: install pkgs
    become: true
    apt: pkg={{ item }} state=present update_cache=true
    with_items:
      - build-essential
      - liblzma-dev
      - libssl-dev
      - zlib1g-dev

  - name: download chefdk
    get_url:
      url: https://packages.chef.io/stable/ubuntu/12.04/{{ chefdk }}
      dest: /home/ubuntu/

  - name: install chefdk
    become: yes
    shell: dpkg -i /home/ubuntu/{{ chefdk }}

  - name: clone openstack chef repo
    git: repo=git://git.openstack.org/openstack/openstack-chef-repo dest=~/openstack-chef-repo

  - name: fetch patchset to check
    shell: git fetch origin {{ patchset_ref }} && git checkout FETCH_HEAD
    args:
      chdir: /home/ubuntu/openstack-chef-repo

  - name: run chef client
    shell: WORKSPACE=/home/ubuntu/logs chef exec rake integration 2>&1 > /tmp/stack.sh.log.out
    args:
      chdir: /home/ubuntu/openstack-chef-repo
    register: stack_result
    ignore_errors: true

  - name: Fetch stack.sh.log.out
    fetch: src=/tmp/stack.sh.log.out dest={{ results_dir }}/stack.sh.log.out flat=yes validate_md5=no

  - name: Fail the stack.sh task
    fail: msg="Failed to complete stack.sh"
    when: stack_result|failed
