- hosts: devstack_instances
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no

  tasks:

  - name: install pkgs
    become: true
    apt: pkg={{ item }} state=present
    with_items:
      - git
      - vim

  - name: clone devstack
    become: no
    git: repo=https://github.com/openstack-dev/devstack dest=~/devstack

  - name: send over local.conf
    become: no
    template: src=../../templates/localconf.base dest=/home/ubuntu/devstack/local.conf

  - name: modify cinder_branch
    lineinfile: dest=/home/ubuntu/devstack/local.conf regexp=^CINDER_BRANCH= line=CINDER_BRANCH={{ patchset_ref }}
    register: git_sha

  - name: run stack.sh
    become: no
    shell: cd /home/ubuntu/devstack; ./stack.sh 2>&1 > /tmp/stack.sh.log.out
    register: stack_result
    ignore_errors: true

  - name: Fetch stack.sh.log.out
    fetch: src=/tmp/stack.sh.log.out dest={{ results_dir }}/stack.sh.log.out flat=yes validate_md5=no

  - name: Fail the stack.sh task
    fail: msg="Failed to complete stack.sh"
    when: stack_result|failed
